### PR TITLE
A few small fixes

### PR DESCRIPTION
**Pull request by canndrew**

### CODE REVIEW

**Comment by dpc** [comment]
Agreed on two changes, but I'm unsure about the `Fn` -> `FnOnce` change.

I thought accepting `Fn` is generally better than `FnOnce` for the user. `FnOnce` can only move variables, while `Fn` can use the outside variables. What's the benefit of `FnOnce`?

**Comment by canndrew** [comment]
Nah, `FnOnce` is strictly more general than `Fn` in this situation. According to [it's docs](https://doc.rust-lang.org/core/ops/trait.FnOnce.html) `impl<'a, A, F: ?Sized> FnOnce<A> for &'a F where F: Fn<A>`. The logic being any function that can be called multiple times can also be called only once. If you don't want to move variables into the closure then just don't use `move`.

**Comment by Drakulix** [comment]
@dpc fn, Fn and FnMut all implement FnOnce. By accepting an FnOnce closure you actually give the user more options instead of forcing unnecessary limitations of the Fn Trait on them.

**Comment by dpc** [comment]
I see! Thanks.

**Comment by dpc** [comment]
BTW. Should sync take FnOnce too?

**Comment by canndrew** [comment]
@dpc: Yeah, I'd say so.

**Pull request merged**
