### PR TITLE
Coroutine user data

### LINKED ISSUE #68: Attach custom data to each Coroutine for Scheduling purposes.
Requested in #36 . Right now `SchedulerThread` can only get the following information about each coroutine:

* id - through `CoroutineControl::id()`
* if it's blocked on `yield_now()` - through `CoroutineControl::is_yielding()`

Being able to attach some custom data (eg. priorities) might greatly simplify custom schedulers job.

### PR DESCRIPTION
**Pull request by Drakulix**
This pull requests adds the feature to add user data to a coroutine, that can be used by a scheduler. 

There are currently three points to discuss before I consider this feature to be ready. This pull request represents a work in progress state and is not meant for merging. These points are:

- ~~Decide if a `start_with` function should be added to be able to add user data to the very first spawned coroutine.~~
- ~~Decide if the current test case is sufficient. It currently does not verify, that `get_user_data` does not always return `None`. This could easily be solved by implementing `start_with` (first point).~~
- [x] Think about finding a way to remove the `as_unsafe_cell` call in `get_user_data`. `borrow_mut` is not working because of lifetime issues, although we know, that the user_data should life as long as the coroutine.

Fixes #68

### CODE REVIEW

**Comment by dpc** [comment]
Some comments after brief review:

* I think spawn should stay as it was and implicitly assume None user data.
* `spawn_with_ext` could be `spawn_with_data`, and if it a way to go, there should be `start_with_data` as well, yes, but...
* ... I am thinking if there could be one call in the parent, that would set the data for child coroutines. This way one `spawn` could be used everywhere. The good part about having just `spawn` is that one can write a function that does something, and spawns a child-coroutine, and does not have to modify it, changing `spawn` to `spawn_with`. Instead a caller would set the data for all the children. In similar fashion in unix children inherit clone of parent environment. This makes the naming easier too.
* I'm fine with unsafe_cell calls as long as they work. If you think this could changed into something better, just add a `// TODO:` and this can be dealt with later.

**Comment by Drakulix** [comment]
- Coroutine::spawn isn't a public api, is it? So why avoid the additional argument here and leave it as it is? The mioco::start and mioco::spawn_ext functions still exist like before next to the new mioco::spawn_with_ext

- Renaming to spawn_with_data sounds good, I am on it

- Although I definitely see the use of inheriting user data (especially when dealing with crates, that are not aware of a custom scheduler), I think that this might be a little confusing for the user. Also I am not sure how you think the parent should be able to set data in the first place, would you mind providing a pseudo-code example for the api you are imagining?

**Comment by Drakulix** [comment]
- Also. I think there is a problem with having just one `spawn` (instead of spawn_with and spawn). The data would not be available for the scheduler on coroutine launch.

**Comment by dpc** [comment]
Ah, I haven't noticed which `spawn` is it. Nevermind then.

I guess I see it as something like:

```
// to set what children will inherit by default
mioco::set_children_userdata(data);
mioco::spawn(|| {
    // to change own data
    mioco::set_userdata
```

It's debatable if there should be two functions (for self, and for future children), or just one. It seems to me two is clear and more flexible (in case the behavior of `spawn` change or something like it).

I guess `Clone` is the way to. One can always use `Arc` or event `Mutex` which do have `Clone` implemented to have it shared between coroutines.

**Comment by Drakulix** [comment]
I am not in favor of setting the user data inside a coroutine. This would mean two things for the scheduler:
- Userdata may change for the same coroutine (which might be confusing and difficult to handle depending on the scheduler). I think only allowing the scheduler to change user_data is a better approach from the API perspective.
- Userdata cannot be set for `Scheduler::spawned` except through set_children_userdata. Which means that the first coroutine will never have any userdata set in `spawned` and that you need to reset the children userdata after spawning every time, if you just wanted to set it for one specific child.

Although I see the problematic with having multiple `spawn` functions, I would still prefer `spawn_with_data` and `start_with_data` functions and adding an additional boolean parameter `inherits`.

```rust
mioco::spawn_with_data(data, true, || { //inherits
    // ...
}
mioco::spawn_with_data(data, false, || { //does not inherit
    // ...
}
```

Another option would be to add those spawn functions and a `set_children_userdata` function instead of the boolean parameter.

Also we need to clarify how deep the inheritance takes place. Do children of children still inherit the user data if set by the parent of the parent? This would make some of our approaches even more difficult, but I guess it would be logical to implement it that way.

**Comment by dpc** [comment]
Isn't changing userdata during a lifetime of coroutine be a commonly used feature? Example usecase: Coroutine switching to lower priority during certain condition?  Alternative would be to spawn a new Coroutine executing the same code, just with different userdata, which seems more cumbersome, or bother scheduler with multiple Coroutine-specific logic to detect such conditions. I'd argue that it's easier for each Coroutine to make decisions about their data, and Scheduler to usually just read the data. CoroutineHandler belongs to Scheduler only when Coroutine is not running, and gets consumed on `fn resume()`, so it shouldn't be really a problem.

There is already a `MiocoConfig` builder pattern, that could accommodate starting userdata for first coroutine.

Bool flags are evil. Let's avoid them. :)

The inheritance deepness is a good question. Maybe it should be an `Option<UserdataType>`, propagating all the way by default, unless someone sets it to `None`? Do you have any useses that this woul be a problem for?

**Comment by dpc** [comment]
One note: It would be great if Schedulers could be generic - you could take a scheduler from an external library, that defines userdata (possibly parametrized by some T, for local use). In this case Scheduler has no way of having a application specific logic in it, so Coroutines must request their own priorities themselves.

**Comment by Drakulix** [comment]
> I'd argue that it's easier for each Coroutine to make decisions about their data, and Scheduler to usually just read the data.
Alright that sounds indeed like a cleaner implementation.
But I would argue, that it should also be possible for the Coroutine to read its own data in that case. So in addition to `set_userdata`, we would also need to have `get_userdata` (also using Clone).

> The inheritance deepness is a good question. Maybe it should be an Option<UserdataType>, propagating all the way by default, unless someone sets it to None? Do you have any useses that this woul be a problem for?

What about not inheriting the user_data by default, but instead passing the parent user_data to the `spawned` function of the scheduler? Then the scheduler may inherit it or not.

> One note: It would be great if Schedulers could be generic - you could take a scheduler from an external library, that defines userdata (possibly parametrized by some T, for local use). In this case Scheduler has no way of having a application specific logic in it, so Coroutines must request their own priorities themselves.

How would that work for the `set_userdata` call? It cannot accept a T, should it return a `Result` in that case?

**Comment by dpc** [comment]
> it should also be possible for the Coroutine to read its own data in that case. 

Agreed.

> What about not inheriting the user_data by default, but instead passing the parent user_data to the spawned function of the scheduler? Then the scheduler may inherit it or not.

Seems OK. But does it work well with idea that scheduler might not know much about application logic?

> How would that work for the set_userdata call? It cannot accept a T, should it return a Result in that case?

Seem OK.

**Comment by Drakulix** [comment]
>> What about not inheriting the user_data by default, but instead passing the parent user_data to the spawned function of the scheduler? Then the scheduler may inherit it or not.

> Seems OK. But does it work well with idea that scheduler might not know much about application logic?

Not sure, most likely not. The co-routine probably knows better, how their children should be prioritized, then the scheduler. I just though, that this would be a nice way around the depth problematic.
I think the best alternative would be inheriting all the way down, unless you explicitly clear the user_data, e.g. by calling `mioco::set_userdata(None);`

**Comment by dpc** [comment]
> I think the best alternative would be inheriting all the way down, unless (...)

Right.

**Comment by Drakulix** [comment]
Okay I am not sure, how much time I will have during the holidays, but I will try to make the discussed changes asap and then ping you again.

**Comment by Drakulix** [comment]
>> How would that work for the set_userdata call? It cannot accept a T, should it return a Result in that case?
> Seem OK.
Its not going to work this way, at least not for a first draft of this feature. The error handling for wrong typed user data will most likely need to be done by the scheduler.

**Comment by Drakulix** [comment]
Okay this is getting more and more difficult.

Since Coroutine cannot be generic, I store user data as Box<Any>. However I cannot create a Box<Any + Clone> or Box<Clone> since Clone is not object-safe. This means I cannot solve this with Clone at all. Passing references is a life-time hell, that is probably not solvable as well. Last thing I could think of is sharing a Arc<Box<Any+Send+Sync>. Any better idea?

**Comment by Drakulix** [comment]
Nope. its not possible. `Arc<Box<Any+Send+Sync>`  it is then?

**Comment by Drakulix** [comment]
Completely new version. Working around that Clone is not object-safe and Coroutine cannot be generic using an Arc<Box<Any+Send+Sync>>. Userdata is now shared instead of cloned.

@dpc Review pls

**Comment by dpc** [comment]
My home family is sick, so my review was rather quick but looks good to me. Good job.

**Comment by Drakulix** [comment]
@dpc Should I rebase against the nowrap branch or what is your plan for merging?

**Comment by dpc** [comment]
Hmm... I think I or you if you'd like can rebase this on top of master when I'm done with nowrap.

**Comment by dpc** [comment]
nowrap has been pushed in master

**Comment by Drakulix** [comment]
Ping @dpc 
I consider this final.

**Comment by dpc** [comment]
All right! It looks good to me. Let's merge.

**Pull request merged**
